name: Deploy Admin

on:
  push:
    branches:
      - admin

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_ADMIN_PROJECT_ID: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Link Vercel Project
        run: |
          npx vercel link --cwd . --yes \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID" \
            --project "$VERCEL_ADMIN_PROJECT_ID"

      - name: Deploy to Production
        run: |
          npx vercel --prod --yes \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID"
